name: Validate and build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - '**'
  
concurrency:
  group: rustgems-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
      - name: fmt validation
        run: |
          cargo fmt -- --check

      - name: clippy validation
        run: |
          cargo clippy --release -- -Dwarnings

      - uses: actions-rs/audit-check@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: extractions/setup-just@v1
      - name: Test
        run: just test-all --release

  build:
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build in release mode
        run: cargo build --release --verbose
