name: Validate and build

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - '**/*.md'
    branches:
      - '**'
  
concurrency:
  group: rustgems-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    runs-on: arc-k3s-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: fmt validation
        run: |
          cargo fmt -- --check

      - name: clippy validation
        run: |
          cargo clippy --release -- -Dwarnings

      - name: cargo audit
        run: |
          cargo audit


  build:
    if: "!contains(github.event.head_commit.message, 'NO_CI')"
    runs-on: arc-k3s-runner-set
    steps:
      - uses: actions/checkout@v4

      - name: Build in release mode
        run: cargo build --release --verbose

      - name: Build in release mode
        run: cargo test
